Finish lesson 19
Codcore/rack pull request #1
Opened 2019-04-12 10:04 UTC by Codcore

2019-04-12 12:16 UTC, BubuntuClu requested changes

2019-04-12 12:16 UTC, BubuntuClu commented on time.rb
> +      @body << DateTime.now.strftime(build_time_string)
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2019-04-12 12:16 UTC, BubuntuClu commented on time.rb
> +      case f
хэш со значениям смотрится симпатичней

2019-04-12 12:16 UTC, BubuntuClu commented on time.rb
> +      when :year then time_string << "%Y-"
разделители можно не указывать. ты можешь подать набор нужных параметров в strftime, а дальше уже сделать `join` с нужным символом

2019-04-12 17:27 UTC, BubuntuClu requested changes

2019-04-12 17:27 UTC, BubuntuClu commented on time_formatter.rb
> +    @status = 200
этот класс не должен знать ни о каких статусах, он просто парсит строку с параметрами и пытается ее преобразовать во время

2019-04-12 17:27 UTC, BubuntuClu commented on time_formatter.rb
> +    { 'Content-Type' => 'text/plain' }
это тоже не функция этого класса. если ты захочешь подключить этот класс в другом проекте, который не будет связан с ответом пользователю, а просто тебе надо будет распарсить строку. то эти все методы там будут лишними.

2019-04-12 17:27 UTC, BubuntuClu commented on time.rb
> +      [formatter.status, formatter.headers, formatter.body]
для ответа можно использовать `Rack::Response`

2019-04-12 17:27 UTC, BubuntuClu commented on time.rb
> +    if request.get? && request.path == "/time" && request.params["format"]
тут у тебя правильно, проверяешь есть ли такой путь, если ли нет, то 404, если есть, тогда уже определяешь отдать ответ временем или 400

2019-04-12 17:27 UTC, BubuntuClu commented on time.rb
> +      formatter.body << DateTime.now.strftime(formatter.build_time_string)
время можно вынести в класс парсинга, это часть бизнесс-логики, rack-класс о ней не должен знать

2019-04-13 05:04 UTC, BubuntuClu commented on time_formatter.rb
> +  def unknown_format(format)
лучше назвать метод с глаголом, сейчас не совсем понятно что это, похоже на сеттер

2019-04-13 05:04 UTC, BubuntuClu commented on time_formatter.rb
> +        unknown_format f.to_s
я предпочитаю скобочки ставить всегда, когда используется метод

2019-04-13 19:57 UTC, psylone approved these changes

2019-04-13 19:57 UTC, psylone commented on config.ru
> +require_relative 'time'
Обычно файл называют также как класс в snake case: `time_app.rb`.

2019-04-13 19:57 UTC, psylone commented on time.rb
> +    if request.get? && request.path == '/time' && request.params['format']
Было бы здорово разделить эту логику на несколько методов:

```ruby
def call(env)
  case request.path
  when '/time'
    time_response
  else
    not_found_response
  end
end
```

2019-04-13 19:57 UTC, psylone commented on time.rb
> +    response.status = 200
По умолчанию статус уже `200`: https://www.rubydoc.info/gems/rack/Rack%2FResponse:initialize

2019-04-13 20:18 UTC, merged